### ISSUE TITLE
ExampleJob has not 'register' method defined.

### ISSUE THREAD

**Issue by CdavM** [peerlibrary/meteor-classy-job#2]
Reading a basic example on your readme it seems that the easiest way to define a custom job is to run

```
class ExampleJob extends Job {
  run() {
    this.logInfo("Hello world from: " + this.data.name);
  }
}

ExampleJob.register();
```

What I have done:
1. Created a test app with Meteor 1.4.1.1; classy-job 0.5 and vsivsi:job-collection  1.4.0.
2. execute `sudo meteor --port 80 run` and in a new terminal window `sudo meteor shell`.
3. run the snippet above which returned the following:

```
TypeError: ExampleJob.register is not a function
    at repl:1:-50
    at packages/shell-server/shell-server.js:458:25
    at /home/masha/.meteor/packages/promise/.0.8.7.1ih0cfk++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:32:39
```

What is the easiest example which creates and runs the ExampleJob?

**Comment by mitar** [comment]
You should never ever run `meteor` with `sudo`.

**Comment by CdavM** [comment]
OK I thought that I needed to add the job-collection package as well. After removing it it seems to work

**Comment by CdavM** [comment]
I'm using `sudo` to access port 80. Any ways to achieve this without `sudo`?

**Comment by mitar** [comment]
You should not be developing on port 80. :-)

**Comment by mitar** [comment]
Yes, you should not be adding `job-collection` package itself because this package uses the same name (`Job`) for the base class, while `job-collection` uses it for their jobs.
