### ISSUE TITLE
API to cancel recurring jobs potentially missing (or underexplained)?

### ISSUE THREAD

**Issue by CdavM** [peerlibrary/meteor-classy-job#3]
I am trying to cancel a job that is scheduled to repeat forever with a certain wait parameter. 

I am currently doing this via:

schedule:
`new ExampleJob({name: "Foo"}).enqueue({repeat: {wait:500}});`

cancel:
`JobsWorker.collection.remove({"data.name": "Foo"})`

But this may not be the best way to achieve this. Could you advise on how to cancel an existing job?

I see that meteor-job-collection package has a method called getJob, so I can do something like getJob({"data.name": "Foo"}).cancel() or .remove().

**Comment by mitar** [comment]
So to schedule repeated jobs I often use:

```
new ExampleJob({name: "Foo"}).enqueue({repeat: {wait:500}, skipIfExisting: true});
```

This assures that I do not schedule multiple repeated jobs at the same time.

Yes, removal from the database directly is not a good idea because you lost state information.

**Comment by mitar** [comment]
I added more methods to help you here and added also an example to the README.

This change is not yet released, so please use `git submodule` to add it to your `packages` and try it out.
